### ISSUE TITLE
Socket Hang-Up Error when Starting Application

### ISSUE THREAD

**Issue by 27136773** [manga-download/hakuneko#14]
Import: https://sourceforge.net/p/hakuneko/tickets/112/
----
I'm trying to start hakuneko but it hangs on the screen "initialzing connectors". I'm on ubuntu 18.10 and installed the latest version hakuneko-desktop_0.4.0_linux_amd64.deb. I ran it from terminal and got this error message:

```
------------------------
Framework Version Info
------------------------
Electron : 2.0.12
Chrome   : 61.0.3163.100
Node     : 8.9.3
------------------------

Checking for update: http://static.hakuneko.download/0.4.0/latest
Local revision: 986d68
Remote revision: a09932
Updating...
{ Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' }
```
Not sure if it's that but I have Chrome not installed. I use Firefox. Is there a fix out there? Thanks in advance!

**Comment by 27136773** [comment]
Your installed browser doesn't matter, this is a common electron/nodejs problem.
I have no fix for that yet...

Probably related: Ticket #13

Only workaround available is to try a manual update...
https://sourceforge.net/p/hakuneko/discussion/support/thread/844ecdaa94/#a811

**Comment by 27136773** [comment]
For the next desktop client the following suggestions may fix this issue:

* new node version
* add `Connection: keep-alive` header
* Do not allow gzip responses (via header or via options)

**Comment by gumbogal** [comment]
This same bug also affects me on Linux Mint 19.1.

**Comment by 27136773** [comment]
New desktop client v5.0.8 has been released last week.
If there are no new reports about HakuNeko getting stucked during loading until October 1st, this issue will be closed.
