### ISSUE TITLE
Ninemanga error

### ISSUE THREAD

**Issue by enriqueism** [manga-download/hakuneko#191]
Error downloading from ninemanga.com
`Fetch API cannot load ninemanga-es://es.ninemanga.com/chapter/Katsute%20Kami%20Datta%20Kemono-tachi%20e/629199-1.html. URL scheme must be "http" or "https" for CORS request.`

**Comment by 27136773** [comment]
Cannot be reproduced, all images can be shown as on the website.
Are you using the latest version of HakuNeko (not the test version)?
Have you tried [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)?

**Comment by enriqueism** [comment]
I'm using a clone from git, updated yesterday. Because I'm unable tu run 0.4.0 deb in Ubuntu 19.40 it freezes trying to download an update
```
Checking for update: http://static.hakuneko.download/0.4.0/latest
Local revision: undefined
Remote revision: 577285
Updating...
{ Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' }

```

**Comment by 27136773** [comment]
Try the current stable `0.4.0` branch instead of the development `master`

**Comment by enriqueism** [comment]
Thanks, this branch works as usual.
