### ISSUE TITLE
[Bug] Running `npm start` fails with message 'Initialization of "UpdateServerManager" failed! TypeError: Cannot read property 'length' of null.'

### ISSUE THREAD

**Issue by robert-7** [manga-download/hakuneko#3167]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Running `npm start` fails with message `Initialization of "UpdateServerManager" failed! TypeError: Cannot read property 'length' of null`.

```plaintext
robert at DESKTOP-JG38EKE in /src/github.com/robert-7/hakuneko on master
$ npm start

> hakuneko-dev@1.0.0 start /src/github.com/robert-7/hakuneko
> npm run start:dev


> hakuneko-dev@1.0.0 start:dev /src/github.com/robert-7/hakuneko
> electron . --update-url=DISABLED --cache-directory=./src/web --disable-http-cache

 2021-03-06T18:28:31.085Z <WARNING>  Initialization of "UpdateServerManager" failed! TypeError: Cannot read property 'length' of null
    at new UpdateServerManager (/src/github.com/robert-7/hakuneko/src/app/UpdateServerManager.js:13:59)
    at new App (/src/github.com/robert-7/hakuneko/src/app/App.js:26:29)
    at Object.<anonymous> (/src/github.com/robert-7/hakuneko/src/app/main.js:3:11)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at loadApplicationPackage (/src/github.com/robert-7/hakuneko/node_modules/electron/dist/resources/default_app.asar/main.js:109:16)
    at Object.<anonymous> (/src/github.com/robert-7/hakuneko/node_modules/electron/dist/resources/default_app.asar/main.js:155:9)

Usage:
  /src/github.com/robert-7/hakuneko/node_modules/electron/dist/electron [OPTIONS]

Options:
  -u, --update-url=<URL>      URL to be checked for web-application updates
                              Default: "http://manga-download.github.io/hakuneko/{version}/latest"
  --startup-url=<URL>         URL to the entrypoint of the web-application
                              Default: "hakuneko://cache/index.html"
  -c, --cache-directory=<DIR> Directory where the web-application is stored
                              Default: system's default
  --user-directory=<DIR>      Directory where user settings are stored
                              Default: system's default


--------------
Framework Info
--------------
Electron : 8.3.4
Chrome   : 80.0.3987.165
Node     : 12.13.0


-------------
Configuration
-------------
Update URL           : DISABLED
Connector Protocol   : connector
Application Protocol : hakuneko
Startup URL          : hakuneko://cache/index.html
AppCache Directory   : /src/github.com/robert-7/hakuneko/src/web
UserData Directory   : /home/robert/.config/hakuneko-dev
```

**To Reproduce**

```bash
cd /src/github.com/robert-7/ && git clone 'https://github.com/manga-download/hakuneko.git' hakuneko
cd /src/github.com/robert-7/hakuneko && npm install
npm start
```

**Expected behavior**
I should not receive any warns on startup.

**Context (please complete the following information):**
 - OS: Ubuntu 20.04 LTS (Focal Fossa) running in Windows Subsystem for Linux 2
 - HakuNeko Version [e.g. 6.17]
 - I'm on commit `c42fb4c4`
```
$ git log -n 1 --oneline
c42fb4c4 (HEAD -> master, upstream/master, origin/master, origin/HEAD) use mobile site for kuaikanmanhua for larger images. (#3155)
```

**Additional context**
Outputting the URL variable just shows an empty object.
```
Url {
  protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  search: null,
  query: [Object: null prototype] {},
  pathname: 'DISABLED',
  path: 'DISABLED',
  href: 'DISABLED'
}
```

**Comment by 27136773** [comment]
It did not fail, it shows a warning that the update could not be performed.

This is intentional. When running HakuNeko for development we do not want to update HakuNeko, which would overwrite the `src` directory, therefore we provide an invalid update URL with `--update-url=DISABLED`
