### ISSUE TITLE
[Bato.to] Website not working

### ISSUE THREAD

**Issue by crhyteacal** [manga-download/hakuneko#4150]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Are you able to see the manga within your browser**
Yes

**Describe the bug**
Every time I tried to download, it got a timeout error

**To Reproduce**
1. Uses clipboad
2. Copied this https://bato.to/series/88392
3. Got 
`ERR_CONNECTION_TIMED_OUT (-118) loading 'https://bato.to/'
    at rejectAndCleanup (D:\hakuneko-desktop_6.1.7_windows-portable_amd64\resources\electron.asar\browser\navigation-controller.js:67:29)
    at WebContents.failListener (D:\hakuneko-desktop_6.1.7_windows-portable_amd64\resources\electron.asar\browser\navigation-controller.js:77:21)
    at WebContents.emit (events.js:205:15)`

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by KunalG-Zol** [comment]
Not sure but the website might have blocked you. To reduce the chances of a website blocking you disable concurrent downloads from the settings. Try using a vpn for now.

**Comment by Sheepux** [comment]
Cannot reproduce: working fine here
