### ISSUE TITLE
javascript warnings? at start up

### ISSUE THREAD

**Issue by wedgingt** [manga-download/hakuneko#638]
Since the latest release, I have been seeing these warnings every time I start hakuneko-desktop on the latest Ubuntu release, all updates before today applied.
I'm also unable to download much of anything, but perhaps that is the captcha issue already opened.

 2019-11-14T03:57:18.489Z <WARNING>  Error: Cannot inject javascript while web-application is not yet ready!
    at AsyncFunction.<anonymous> (/usr/lib/hakuneko-desktop/resources/app.asar/ElectronBootstrap.js:201:27) 
 2019-11-14T03:57:18.494Z <WARNING>  Error: Cannot inject javascript while web-application is not yet ready!
    at AsyncFunction.<anonymous> (/usr/lib/hakuneko-desktop/resources/app.asar/ElectronBootstrap.js:201:27) 
 2019-11-14T03:57:18.495Z <WARNING>  Error: Cannot inject javascript while web-application is not yet ready!
    at AsyncFunction.<anonymous> (/usr/lib/hakuneko-desktop/resources/app.asar/ElectronBootstrap.js:201:27) 
 2019-11-14T03:57:18.495Z <WARNING>  Error: Cannot inject javascript while web-application is not yet ready!
    at AsyncFunction.<anonymous> (/usr/lib/hakuneko-desktop/resources/app.asar/ElectronBootstrap.js:201:27) 
 2019-11-14T03:57:18.742Z <WARNING>  Error: Cannot inject javascript while web-application is not yet ready!
    at AsyncFunction.<anonymous> (/usr/lib/hakuneko-desktop/resources/app.asar/ElectronBootstrap.js:230:27) 
 2019-11-14T03:57:18.746Z <WARNING>  Error: Cannot inject javascript while web-application is not yet ready!
    at AsyncFunction.<anonymous> (/usr/lib/hakuneko-desktop/resources/app.asar/ElectronBootstrap.js:230:27) 
 2019-11-14T03:57:18.869Z <WARNING>  Error: Cannot inject javascript while web-application is not yet ready!
    at AsyncFunction.<anonymous> (/usr/lib/hakuneko-desktop/resources/app.asar/ElectronBootstrap.js:230:27) 
 2019-11-14T03:57:19.027Z <WARNING>  Error: Cannot inject javascript while web-application is not yet ready!
    at AsyncFunction.<anonymous> (/usr/lib/hakuneko-desktop/resources/app.asar/ElectronBootstrap.js:230:27)

**Comment by 27136773** [comment]
Those warnings are expected and have no impact on usability.

For download issues please perform the following tasks first and let us know if the problem still exist:

- [ ]  New to HakuNeko? You may look into the [**Quick Start**](https://github.com/manga-download/hakuneko/wiki/Quick-Reference)
- [ ]  Some common problems may be solved by [**Troubleshooting**](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)
- [ ]  Also check if the [**Manual Website Interaction**](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction) works
- [ ]  Try [**Search**](https://github.com/manga-download/hakuneko/issues?utf8=%E2%9C%93&q=TOPIC) for similar issues, which may already solve your problem
- [ ]  Provide the **website + manga + chapter** to reproduce the problem

--
_Please **do not** create a new ticket for replies_

**Comment by wedgingt** [comment]
The solution mentioned in https://github.com/manga-download/hakuneko/issues/634 resolved my download issue, at least from KissManga - I haven't had time to try others yet.

**Comment by 27136773** [comment]
Closed for now for any other issues please create a new ticket
