### ISSUE TITLE
White Screening on LinuxMint 19.2

### ISSUE THREAD

**Issue by MilesNegrete** [manga-download/hakuneko#686]
If I launch it from the terminal, I get
`{ Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' }
`
I have looked at other solutions and it mentions putting the new version into the cache folder, but it looks like I do not have one.

**Comment by 27136773** [comment]
Are you using 5.0.8 or the latest Nightly Build?

**Comment by 27136773** [comment]
Related:
#13 
#14

**Comment by 27136773** [comment]
No further response => closed
