### ISSUE TITLE
KissComics Can't Download

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#813]
> **From:** HakuNeko User

Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at WebFrame.<computed> (C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\api\web-frame.js:64:33)
    at WebFrame.executeJavaScript (C:\Program Files\HakuNeko Desktop\resources\electron.asar\common\api\deprecate.js:114:32)
    at C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\web-frame-init.js:11:43
    at C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\ipc-renderer-internal-utils.js:7:40
    at new Promise (<anonymous>)
    at EventEmitter.<anonymous> (C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\ipc-renderer-internal-utils.js:7:9)
    at EventEmitter.emit (events.js:200:13)
    at Object.onMessage (C:\Program Files\HakuNeko Desktop\resources\electron.asar\renderer\init.js:42:16)

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
Cannot be reproduced based on the given information (HakuNeko Version, Manga, Chapter, ...).

<img width="1232" alt="Screen Shot 2020-01-01 at 1 38 50 PM" src="https://user-images.githubusercontent.com/27136773/71641431-16f69300-2c9c-11ea-8f67-6e13ab2e97cf.png">
